### ISSUE TITLE
Epub table formatting, ch. 1

### ISSUE THREAD

**Issue by skovsgaard** [mixu/distsysbook#39]
On page 9 of the epub, there is what I assume is supposed to be a table of availability, and what downtime per year that translates to. In the current epub, this is just a list:

> Availability %
> 
> How much downtime is allowed per year? 
> 
> 90% ("one nine")
> 
> More than a month
> 
> 99% ("two nines")
> 
> Less than 4 days
> 
> 99.9% ("three nines")
> 
> Less than 9 hours
> 
> (...)

If this is by design, feel free to just close this.

**Comment by mixu** [comment]
thanks for filing this - it's not by design, but I don't really have the resources to manually format the epub version, which is basically converted from the single page html via Calibre. It is a table in the original markup so Calibre should be smart enough to tableify it in the epub, but I guess that's not the case here...

**Comment by skovsgaard** [comment]
So I guess that makes it can't fix, which is fine. I just wanted to let you know in case there was a way to make it work.
